---
title: "Evolución del Rendimiento de los Jugadores de la NBA (2014-2024)"
output: pdf_document
date: "2025-03-02"
lang: es
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readxl)
library(knitr)
library(gt)
library(patchwork)
#tinytex::install_tinytex(force = TRUE)
Data_Frame_NBA <-read_excel("D:\\NBA G1-G10.xlsx","BBDD")
```

## Datos Mas Importantes

```{r echo=FALSE,message= FALSE, warning=FALSE,fig.width=20}
#Faltrado Por temporada, unicamente desde 1014 hasta 2024
Datos_Por_Temporada <- Data_Frame_NBA %>%
  filter(Season >= "2014-15" & Season <= "2024-25")

Estadisticas_Generales <- function(Equipo){
  Datos_Por_Temporada %>%
    filter(Team == Equipo)%>%
    select(Season,Team, W, L, GP, PTS)%>%
    summarize(
      Team = case_when(
        Equipo == "BOS"~"Boston Celtics",#1
        Equipo == "ATL"~"Atlanta Hawks",#2
        Equipo == "BKN"~"Brooklyn Nets",#3
        Equipo == "CHA"~"Charlotte Hornets",#4
        Equipo == "CHI"~"Chicago Bulls",#5
        Equipo == "DAL"~"Dallas Mavericks",#6
        Equipo == "CLE"~"Cleveland Cavaliers",#7
        Equipo == "DET"~"Detroit Pistons",#8
        Equipo == "DEN"~"Denver Nuggets",#9
        Equipo == "GSW"~"Golden State Warriors",#10
        Equipo == "HOU"~"Houston Rockets",#11
        Equipo == "IND"~"Indiana Pacers",#12
        Equipo == "LAC"~"Los Angeles Clippers",#13
        Equipo == "LAL"~"Los Angeles Lakers",#14
        Equipo == "MEM"~"Memphis Grizzlies",#15
        Equipo == "MIA"~"Miami Heat",#16
        Equipo == "MIL"~"Milwaukee Bucks",#17
        Equipo == "MIN"~"Minnesota Timberwolves",#18
        Equipo == "NOP"~"New Orleans Pelicans",#19
        Equipo == "NYK"~"New York Knicks",#20
        Equipo == "OKC"~"Oklahoma City Thunder",#21
        Equipo == "ORL"~"Orlando Magic",#22
        Equipo == "PHI"~"Philadelphia 76ers",#23
        Equipo == "PHX"~"Phoenix Suns",#24
        Equipo == "POR"~"Portland Trail Blazers",#25
        Equipo == "SAC"~"Sacramento Kings",#26
        Equipo == "SAS"~"San Antonio Spurs",#27
        Equipo == "TOR"~"Toronto Raptors",#28
        Equipo == "UTA"~"Utah Jazz",#29
        Equipo == "WAS"~"Washington Wizards"#30
      ),
      Porm_PJ = mean(GP, na.rm = T),
      Prom_PG = mean(W, na.rm = T),
      Prom_PP = mean(L, na.rm = T),
      Prom_PTS = mean(PTS, na.rm = T),
      #Tiro_Porcentaje = mean(FG%, na.rm =T)
    )
}
# Aplicar la función a cada equipo
equipos <- c("BOS", "ATL", "BKN", "CHA","CHI","CLE","DAL","DEN","DET","GSW","HOU","IND","LAC","LAL","MEM","MIA","MIL","MIN","NOP","NYK","OKC","ORL","PHI","PHX","POR","SAC","SAS","TOR","UTA","WAS")

Datos_a_Comparar <- lapply(equipos, Estadisticas_Generales) %>%
  bind_rows()

# Mostrar la tabla
kable(Datos_a_Comparar, caption = "Tabla comparativa general por equipo", digits = 1)
```

## Presentacion de Variables

```{r ,echo=FALSE,width= 4, fig.height= 4}
Datos_Por_Temporada <- Data_Frame_NBA %>%
  filter(Season >= "2014-15" & Season <= "2024-25")

Graficos_Pos_BOS <- Datos_Por_Temporada %>%
  filter(Team == "BOS")%>%
  ggplot(aes(Position, fill= Position))+
  geom_bar()+
  scale_fill_manual(values = c("#fbcd00","#ef8207","#b30808"))+
  theme_bw()+
  guides(fill = guide_legend(title = "Posiciones"))+
  labs(title = "Boston Celtis")

Graficos_Pos_ATL <- Datos_Por_Temporada %>%
  filter(Team == "ATL")%>%
  ggplot(aes(Position, fill= Position))+
  geom_bar()+
  scale_fill_manual(values = c("#fbcd00","#ef8207","#b30808"))+
  theme_bw()+
  guides(fill = guide_legend(title = "Posiciones"))+
  labs(title = "Atlanta Haws")

print(Graficos_Pos_BOS + Graficos_Pos_ATL)
```